name: gh-pages

on:
  push:
  workflow_dispatch:

# https://docs.github.com/zh/actions/using-jobs/assigning-permissions-to-jobs
permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    name: Build depoly files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Building ...
        run: |
          yarn
          yarn build
          touch dist/.nojekyll
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist